# Use an official Golang runtime as a parent image
FROM golang:latest
RUN apt-get update && \
    apt-get install -y awscli && \
    rm -rf /var/lib/apt/lists/*
# Set the working directory inside the container
WORKDIR /app

# Copy the local source files into the container
COPY . .

WORKDIR /app

RUN go build -o translator

# Expose ports 7001-7012 for the application
EXPOSE 7008

# Command to run the Go application
CMD ["./translator"]